database:
  driver: "ODBC Driver 17 for SQL Server"
  server: "244-NGUYEN-QUAN\\SQL2022"
  database: "Book"
  trusted_connection: true
  encrypt: false

swagger:
  headers: []
  title: "Book API Demo"
  version: "1.0.0"
  description: "API minh họa lỗi N+1 và cách tối ưu với SQLAlchemy"
  termsOfService: ""
  contact:
    name: "Nguyễn Mạnh Quân"
    email: "22028171@vnu.edu.vn"
  license:
    name: "MIT"
  specs:
    - endpoint: 'apispec_1'
      route: '/apispec_1.json'
  static_url_path: "/flasgger_static"
  specs_route: "/swagger/"
  securityDefinitions:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: "JWT Authorization header using the Bearer scheme. Ví dụ: 'Bearer {token}'"